### ISSUE TITLE
国家局：标题栏背景图片

### ISSUE THREAD

**Issue by DragonCloudsBai** [sinoui/sino-intellisense-form#647]
![image](https://user-images.githubusercontent.com/11955014/83868501-8f86e180-a75d-11ea-805d-4409c050e7a2.png)
智能表单标题栏背景图片希望能与设备申请项目相同
![head_bj](https://user-images.githubusercontent.com/11955014/83868595-be04bc80-a75d-11ea-9521-f47809970959.png)

**Comment by liujinxing** [comment]
新增`appBarBgUrl`和`appBarBgColor`参数，指定一个应用程序栏的背景图片链接和背景色。使用方式如下：

```
http://localhost:8080/intellisense-form/xxx/home?appBarBgUrl=http://localhost:8089/bg.gif&appBarBgColor=#c7e9f6
```

在实现时，采用背景居中不重复的方式，如：

```css
.appbar {
  background: url(http://localhost:8089/bg.gif) center #c7e9f6 no-repeat; 
}
```
